---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: planet-express
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/J-Thompson12/planet-express.git

